/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as AppEventsEventIdRouteImport } from './routes/_app.events.$eventId'
import { Route as AppEventsNewRouteImport } from './routes/_app.events.new'
import { Route as AppSummariesSummaryIdRouteImport } from './routes/_app.summaries.$summaryId'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/_app.events.$eventId.index'
import { Route as AppEventsEventIdConnectRouteImport } from './routes/_app.events.$eventId.connect'
import { Route as AppEventsEventIdEditRouteImport } from './routes/_app.events.$eventId.edit'
import { Route as AppEventsEventIdGuideRouteImport } from './routes/_app.events.$eventId.guide'
import { Route as AppEventsEventIdNavigateRouteImport } from './routes/_app.events.$eventId.navigate'
import { Route as AppEventsEventIdReassessRouteImport } from './routes/_app.events.$eventId.reassess'
import { Route as AppEventsEventIdSafetyRouteImport } from './routes/_app.events.$eventId.safety'
import { Route as AppEventsEventIdSummaryNewRouteImport } from './routes/_app.events.$eventId.summary.new'
import { Route as AppEventsEventIdTrackTodayRouteImport } from './routes/_app.events.$eventId.track.today'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSummariesSummaryIdRoute = AppSummariesSummaryIdRouteImport.update({
  id: '/summaries/$summaryId',
  path: '/summaries/$summaryId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdConnectRoute = AppEventsEventIdConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdEditRoute = AppEventsEventIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdGuideRoute = AppEventsEventIdGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdNavigateRoute =
  AppEventsEventIdNavigateRouteImport.update({
    id: '/navigate',
    path: '/navigate',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const AppEventsEventIdReassessRoute =
  AppEventsEventIdReassessRouteImport.update({
    id: '/reassess',
    path: '/reassess',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const AppEventsEventIdSafetyRoute = AppEventsEventIdSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdSummaryNewRoute =
  AppEventsEventIdSummaryNewRouteImport.update({
    id: '/summary/new',
    path: '/summary/new',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const AppEventsEventIdTrackTodayRoute =
  AppEventsEventIdTrackTodayRouteImport.update({
    id: '/track/today',
    path: '/track/today',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/events/new': typeof AppEventsNewRoute
  '/summaries/$summaryId': typeof AppSummariesSummaryIdRoute
  '/events/$eventId/connect': typeof AppEventsEventIdConnectRoute
  '/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/events/$eventId/guide': typeof AppEventsEventIdGuideRoute
  '/events/$eventId/navigate': typeof AppEventsEventIdNavigateRoute
  '/events/$eventId/reassess': typeof AppEventsEventIdReassessRoute
  '/events/$eventId/safety': typeof AppEventsEventIdSafetyRoute
  '/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/events/$eventId/summary/new': typeof AppEventsEventIdSummaryNewRoute
  '/events/$eventId/track/today': typeof AppEventsEventIdTrackTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/events/new': typeof AppEventsNewRoute
  '/summaries/$summaryId': typeof AppSummariesSummaryIdRoute
  '/events/$eventId/connect': typeof AppEventsEventIdConnectRoute
  '/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/events/$eventId/guide': typeof AppEventsEventIdGuideRoute
  '/events/$eventId/navigate': typeof AppEventsEventIdNavigateRoute
  '/events/$eventId/reassess': typeof AppEventsEventIdReassessRoute
  '/events/$eventId/safety': typeof AppEventsEventIdSafetyRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/events/$eventId/summary/new': typeof AppEventsEventIdSummaryNewRoute
  '/events/$eventId/track/today': typeof AppEventsEventIdTrackTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/summaries/$summaryId': typeof AppSummariesSummaryIdRoute
  '/_app/events/$eventId/connect': typeof AppEventsEventIdConnectRoute
  '/_app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/_app/events/$eventId/guide': typeof AppEventsEventIdGuideRoute
  '/_app/events/$eventId/navigate': typeof AppEventsEventIdNavigateRoute
  '/_app/events/$eventId/reassess': typeof AppEventsEventIdReassessRoute
  '/_app/events/$eventId/safety': typeof AppEventsEventIdSafetyRoute
  '/_app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/_app/events/$eventId/summary/new': typeof AppEventsEventIdSummaryNewRoute
  '/_app/events/$eventId/track/today': typeof AppEventsEventIdTrackTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/login'
    | '/register'
    | '/events/$eventId'
    | '/events/new'
    | '/summaries/$summaryId'
    | '/events/$eventId/connect'
    | '/events/$eventId/edit'
    | '/events/$eventId/guide'
    | '/events/$eventId/navigate'
    | '/events/$eventId/reassess'
    | '/events/$eventId/safety'
    | '/events/$eventId/'
    | '/events/$eventId/summary/new'
    | '/events/$eventId/track/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/login'
    | '/register'
    | '/events/new'
    | '/summaries/$summaryId'
    | '/events/$eventId/connect'
    | '/events/$eventId/edit'
    | '/events/$eventId/guide'
    | '/events/$eventId/navigate'
    | '/events/$eventId/reassess'
    | '/events/$eventId/safety'
    | '/events/$eventId'
    | '/events/$eventId/summary/new'
    | '/events/$eventId/track/today'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/dashboard'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_app/events/$eventId'
    | '/_app/events/new'
    | '/_app/summaries/$summaryId'
    | '/_app/events/$eventId/connect'
    | '/_app/events/$eventId/edit'
    | '/_app/events/$eventId/guide'
    | '/_app/events/$eventId/navigate'
    | '/_app/events/$eventId/reassess'
    | '/_app/events/$eventId/safety'
    | '/_app/events/$eventId/'
    | '/_app/events/$eventId/summary/new'
    | '/_app/events/$eventId/track/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/summaries/$summaryId': {
      id: '/_app/summaries/$summaryId'
      path: '/summaries/$summaryId'
      fullPath: '/summaries/$summaryId'
      preLoaderRoute: typeof AppSummariesSummaryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId/': {
      id: '/_app/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events/$eventId/connect': {
      id: '/_app/events/$eventId/connect'
      path: '/connect'
      fullPath: '/events/$eventId/connect'
      preLoaderRoute: typeof AppEventsEventIdConnectRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events/$eventId/edit': {
      id: '/_app/events/$eventId/edit'
      path: '/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AppEventsEventIdEditRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events/$eventId/guide': {
      id: '/_app/events/$eventId/guide'
      path: '/guide'
      fullPath: '/events/$eventId/guide'
      preLoaderRoute: typeof AppEventsEventIdGuideRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events/$eventId/navigate': {
      id: '/_app/events/$eventId/navigate'
      path: '/navigate'
      fullPath: '/events/$eventId/navigate'
      preLoaderRoute: typeof AppEventsEventIdNavigateRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events/$eventId/reassess': {
      id: '/_app/events/$eventId/reassess'
      path: '/reassess'
      fullPath: '/events/$eventId/reassess'
      preLoaderRoute: typeof AppEventsEventIdReassessRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events/$eventId/safety': {
      id: '/_app/events/$eventId/safety'
      path: '/safety'
      fullPath: '/events/$eventId/safety'
      preLoaderRoute: typeof AppEventsEventIdSafetyRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events/$eventId/summary/new': {
      id: '/_app/events/$eventId/summary/new'
      path: '/summary/new'
      fullPath: '/events/$eventId/summary/new'
      preLoaderRoute: typeof AppEventsEventIdSummaryNewRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events/$eventId/track/today': {
      id: '/_app/events/$eventId/track/today'
      path: '/track/today'
      fullPath: '/events/$eventId/track/today'
      preLoaderRoute: typeof AppEventsEventIdTrackTodayRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
  }
}

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdConnectRoute: typeof AppEventsEventIdConnectRoute
  AppEventsEventIdEditRoute: typeof AppEventsEventIdEditRoute
  AppEventsEventIdGuideRoute: typeof AppEventsEventIdGuideRoute
  AppEventsEventIdNavigateRoute: typeof AppEventsEventIdNavigateRoute
  AppEventsEventIdReassessRoute: typeof AppEventsEventIdReassessRoute
  AppEventsEventIdSafetyRoute: typeof AppEventsEventIdSafetyRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
  AppEventsEventIdSummaryNewRoute: typeof AppEventsEventIdSummaryNewRoute
  AppEventsEventIdTrackTodayRoute: typeof AppEventsEventIdTrackTodayRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdConnectRoute: AppEventsEventIdConnectRoute,
  AppEventsEventIdEditRoute: AppEventsEventIdEditRoute,
  AppEventsEventIdGuideRoute: AppEventsEventIdGuideRoute,
  AppEventsEventIdNavigateRoute: AppEventsEventIdNavigateRoute,
  AppEventsEventIdReassessRoute: AppEventsEventIdReassessRoute,
  AppEventsEventIdSafetyRoute: AppEventsEventIdSafetyRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
  AppEventsEventIdSummaryNewRoute: AppEventsEventIdSummaryNewRoute,
  AppEventsEventIdTrackTodayRoute: AppEventsEventIdTrackTodayRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppSummariesSummaryIdRoute: typeof AppSummariesSummaryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
  AppEventsNewRoute: AppEventsNewRoute,
  AppSummariesSummaryIdRoute: AppSummariesSummaryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
