// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnlbqlzvhplitmwgkhys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubGJxbHp2aHBsaXRtd2draHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1ODM2NjUsImV4cCI6MjEwMjE1OTY2NX0.F-A2bJx0yaPCqokM__ZrBtFVvWo8USYOZ4EwzwZWtO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});